#!/bin/bash

usage() {
    printf "Usage (vol): audioutil vol <cycle-default-sink|get-default-sink|inc|dec|mute|get>\n"
    printf "Usage (media): audioutil media <prev|toggle|next>\n"
    printf "Requires: playerctl, pamixer, and pactl\n"
    exit 1
}

cache() {
    case $1 in
        read)
            cat "$HOME/.cache/audioutil/vol/$2"
            ;;

        write)
            echo "$3" > "$HOME/.cache/audioutil/vol/$2"
            ;;

        *)
            exit 1
            ;;
    esac
}

# TODO: Make this mess cache the sink names, descriptions, numbers, etc

default_sink_num() {
    pamixer --get-default-sink | tail -1 | awk '{ print $1 }'
}

default_sink_desc() {
    pamixer --get-default-sink | tail -1 | cut -d ' ' -f 3- | tr -d '"'
}

default_sink_name() {
    pamixer --get-default-sink | tail -1 | awk '{ print $2 }' | tr -d '"'
}

glava_index() {
    # TODO: Use awk for printing the first line only instead of having to use head as well
    pactl list source-outputs | awk '/Source Output|application.name = "glava"/ { print $3 }' | head -1 | tr -d '#'
}

adjust_vol() {
    vol="$(pamixer --get-volume-human)"
    
    if [[ "$vol" == "muted" && "$1" != "-t" ]]; then
        exit 0
    fi

    sink_desc="$(default_sink_desc)"

    pamixer --allow-boost $1
    
    vol="$(pamixer --get-volume-human)"
    
    prefix=" "
    notif_content="Volume: "

    if [ "$vol" = "muted" ]; then
        prefix=" "
        notif_content+="Muted"
    else
        notif_content+="${vol}"
    fi

    notif "$prefix$sink_desc" "$notif_content"
}

change_sink() {
    sink="$(default_sink_num)"
    max_sink="$(pamixer --list-sinks | tail -1 | awk '{ print $1 }')"

    case $1 in
        inc)
            new_sink="$(expr "$sink" + 1)"
            ;;

        dec)
            new_sink="$(expr "$sink" - 1)"
            ;;

        *)
            exit 1
            ;;
    esac

    if [[ "$new_sink" < 0 ]]; then
        new_sink="$max_sink"
    elif [[ "$new_sink" > "$max_sink" ]]; then
        new_sink="0"
    fi

    pactl set-default-sink "$new_sink"

    new_sink_name="$(default_sink_name)"
    new_sink_desc="$(default_sink_desc)"
    
    if pgrep -x glava; then
        pactl move-source-output "$(glava_index)" "${new_sink_name}.monitor"
    fi

    notif "Sink changed" "<u>${new_sink_desc} (#$new_sink)</u>\nhas been selected as the default sink"
}

notif() {
    icon="placeholder"
    if [ $3 ]; then
        icon="$3"
    fi

    time="2000"
    if [ $4 ]; then
        time="$4"
    fi

    # this hint allows the notification to replace previous confirmation notifications
    dunstify -h "string:x-canonical-private-synchronous:anything" -a "audioutil" -i "$icon" -u "normal" -t "$time" "$1" "$2"
}

if [[ ! $1 ]]; then
    usage
fi

if [[ ! $2 ]]; then
    usage
fi

case $1 in
    vol)
        case $2 in
            inc-default-sink)
                change_sink inc
                ;;

            dec-default-sink)
                change_sink dec
                ;;

            get-default-sink)
                default_sink_num
                ;;

            inc)
                adjust_vol "-i 4"
                ;;

            dec)
                adjust_vol "-d 4"
                ;;

            mute)
                adjust_vol "-t"
                ;;

            get)
                pamixer --get-volume-human
                ;;

            get-polybar)
                result="$(pamixer --get-volume-human)"

                if [[ "$result" == "muted" ]]; then
                    result="%{F#607279}${result}%{F-}"
                fi

                echo "$result"
                ;;

            *)
                usage
                ;;
        esac
        ;;
          
    media)
        case $2 in
            prev)
                playerctl previous
                ;;
            
            toggle)
                playerctl play-pause
                ;;

            next)
                playerctl next
                ;;

            *)
                usage
                ;;
        esac
        ;;

    *)
        usage
        ;;
esac
