#!/bin/bash

usage() {
    printf "Usage (vol): audioutil vol <cycle-default-sink|get-default-sink|inc|dec|mute|get>\n"
    printf "Usage (media): audioutil media <prev|toggle|next>\n"
    printf "Requires: playerctl, pamixer, and pactl\n"
    exit 1
}

default_sink_num() {
    pamixer --list-sinks | grep "$(pamixer --get-default-sink | tail -1 | awk '{ print $2 }' | tr -d '"')" | awk '{ print $1 }'
}

sink_desc_from_num() {
    pactl list sinks | grep -e 'Sink' -e 'Description:' | grep -e "#$1" -A 1 | grep 'Description' | cut -d' ' -f 2-
}

sink_name_from_num() {
    pactl list sinks | grep -e 'Sink' -e 'Name:' | grep -e "#$1" -A 1 | grep 'Name' | cut -d' ' -f 2-
}

glava_index() {
    glavautil get-recording-index
}

adjust_vol() {
    sink="$(default_sink_num)"
    sink_desc="$(sink_desc_from_num $sink)"
    
    pamixer --sink $sink --allow-boost $1
    
    vol="$(audioutil vol get)"

    prefix=" "
    notif_content="Volume: "

    if [ "$vol" = "muted" ]; then
        prefix=" "
        notif_content+="Muted"
    else
        notif_content+="${vol}"
    fi

    notif "$prefix$sink_desc" "$notif_content"
}

change_sink() {
    sink="$(default_sink_num)"
    max_sink="$(pamixer --list-sinks | tail -1 | awk '{ print $1 }')"

    case $1 in
        inc)
            new_sink="$(expr "$sink" + 1)"
            ;;

        dec)
            new_sink="$(expr "$sink" - 1)"
            ;;

        *)
            exit 1
            ;;
    esac

    if [[ "$new_sink" < 0 ]]; then
        new_sink="$max_sink"
    elif [[ "$new_sink" > "$max_sink" ]]; then
        new_sink="0"
    fi

    new_sink_name="$(sink_name_from_num "$new_sink")"
    new_sink_desc="$(sink_desc_from_num "$new_sink")"

    pactl set-default-sink "$new_sink"
    
    if pgrep -x glava; then
        pactl move-source-output "$(glava_index)" "${new_sink_name}.monitor"
    fi

    notif "Sink changed" "<u>${new_sink_desc} (#$new_sink)</u>\nhas been selected as the default sink"
}

notif() {
    icon="placeholder"
    if [ $3 ]; then
        icon="$3"
    fi

    time="2000"
    if [ $4 ]; then
        icon="$4"
    fi

    # this hint allows the notification to replace previous confirmation notifications
    dunstify -h "string:x-canonical-private-synchronous:anything" -a "audioutil" -i "$icon" -u "normal" -t "$time" "$1" "$2"
}

if [[ ! $1 ]]; then
    usage
fi

if [[ ! $2 ]]; then
    usage
fi

case $1 in
    vol)
        case $2 in
            inc-default-sink)
                change_sink inc
                ;;

            dec-default-sink)
                change_sink dec
                ;;

            get-default-sink)
                default_sink_num
                ;;

            inc)
                if [[ "$(audioutil vol get)" != "muted" ]]; then
                    adjust_vol "-i 2"
                fi
                ;;

            dec)
                if [[ "$(audioutil vol get)" != "muted" ]]; then
                    adjust_vol "-d 2"
                fi                
                ;;

            mute)
                adjust_vol "-t"
                ;;

            get)
                pamixer --get-volume-human
                ;;

            get-polybar)
                result="$(pamixer --get-volume-human)"

                if [[ "$result" == "muted" ]]; then
                    result="%{F#607279}${result}%{F-}"
                fi

                echo "$result"
                ;;

            *)
                usage
                ;;
        esac
        ;;
          
    media)
        case $2 in
            prev)
                playerctl previous
                ;;
            
            toggle)
                playerctl play-pause
                ;;

            next)
                playerctl next
                ;;

            *)
                usage
                ;;
        esac
        ;;

    *)
        usage
        ;;
esac
