#!/bin/bash

usage() {
    printf "Usage: glavautil <toggle|start>\n"
    exit 1
}

kill() {
    killall -q glava
}

start() {
    glava -d &
}

if [[ ! $1 ]]; then
    usage
fi

case $1 in
    start)
        kill
        start
        ;;

    toggle)
        if pgrep -x glava > /dev/null; then
            kill
        else
            start
        fi
        ;;

    *)
        usage
        ;;
esac
