#!/bin/bash

usage() {
    printf "Usage: glavautil <toggle|start|get-recording-index>\n"
    exit 1
}

kill() {
    killall -q glava
}

start() {
    glava -d &
}

notif() {
    icon="placeholder"
    if [ $3 ]; then
        icon="$3"
    fi

    time="2000"
    if [ $4 ]; then
        icon="$4"
    fi

    # this hint allows the notification to replace previous confirmation notifications
    dunstify -h "string:x-canonical-private-synchronous:anything" -a "glavautil" -i "$icon" -u "normal" -t "$time" "$1" "$2"
}

if [[ ! $1 ]]; then
    usage
fi

case $1 in
    start)
        kill
        start
        ;;

    toggle)
        if pgrep -x glava > /dev/null; then
            kill
            notif "Audio Visualizer Toggle" "Audio visualizer toggled off"
        else
            start
            notif "Audio Visualizer Toggle" "Audio visualizer toggled on"
        fi
        ;;

    get-recording-index)
        pactl list source-outputs | grep -e 'Source Output' -e 'glava' | grep -e "audio for glava" -B 1 | grep -e 'Source Output' | tr -d '#' | awk '{ print $3 }'
        ;;

    *)
        usage
        ;;
esac
