#!/bin/bash

usage() {
    printf "Usage: glavautil <toggle|start|get-recording-index>\n"
    exit 1
}

kill() {
    killall -q glava
}

start() {
    glava -d &
}

if [[ ! $1 ]]; then
    usage
fi

case $1 in
    start)
        kill
        start
        ;;

    toggle)
        if pgrep -x glava > /dev/null; then
            kill
        else
            start
        fi
        ;;

    get-recording-index)
        pactl list source-outputs | grep -e 'Source Output' -e 'glava' | grep -e "audio for glava" -B 1 | grep -e 'Source Output' | tr -d '#' | awk '{ print $3 }'
        ;;

    *)
        usage
        ;;
esac
