#!/bin/bash

usage() {
    printf "Usage (vol): mediautil vol <cycle-sink|get-sink|inc|dec|mute|get>\n"
    printf "Usage (media): mediautil media <prev|toggle|next>\n"
    printf "Requires: playerctl, pamixer, pactl\n"
    exit 1
}

if [[ ! $1 ]]; then
    usage
fi

if [[ ! $2 ]]; then
    usage
fi

case $1 in
    vol)
        case $2 in
            cycle-sink)
                notify-send "unimplemented feature"
                ;;

            get-sink)
                pamixer --get-default-sink
                ;;

            inc)
                pamixer --sink 2 --allow-boost -i 4
                ;;

            dec)
                pamixer --sink 2 --allow-boost -d 4
                ;;

            mute)
                pamixer --sink 2 -t
                ;;

            get)
                echo "${$(pamixer --sink 2 --get-volume-human)/\%/}"
                ;;
            *)
                usage
                ;;
        esac
        ;;
          
    media)
        case $2 in
            prev)
                playerctl previous
                ;;
            
            toggle)
                playerctl play-pause
                ;;

            next)
                playerctl next
                ;;

            *)
                usage
                ;;
        esac
        ;;

    *)
        usage
        ;;
esac
