#!/bin/bash

usage() {
    printf "Usage: polybarutil <start|toggle>\n"
    exit
}

kill() {
    killall -q polybar
}

start() {
    polybar -rq -c /home/$(whoami)/.config/herbstluftwm/polybar/config.ini bar &
}

if [[ ! $1 ]]; then
    usage
fi

case $1 in
    start)
        kill
        start
        ;;

    toggle)
        if pgrep -x polybar > /dev/null; then
            kill
        else
            start
        fi
        ;;

    *)
        usage
        ;;
esac
