#!/bin/bash

usage() {
    printf "Usage: polybarutil <start|toggle>\n"
    exit
}

kill() {
    killall -q polybar
}

start() {
    polybar -rq -c /home/$(whoami)/.config/herbstluftwm/polybar/config.ini bar &
}

notif() {
    icon="placeholder"
    if [ $3 ]; then
        icon="$3"
    fi

    time="2000"
    if [ $4 ]; then
        icon="$4"
    fi

    # this hint allows the notification to replace previous confirmation notifications
    dunstify -h "string:x-canonical-private-synchronous:anything" -a "polybarutil" -i "$icon" -u "normal" -t "$time" "$1" "$2"
}

if [[ ! $1 ]]; then
    usage
fi

case $1 in
    start)
        kill
        start
        ;;

    toggle)
        if pgrep -x polybar > /dev/null; then
            kill
            notif "Status Bar" "Polybar disabled"
        else
            start
            notif "Status Bar" "Polybar enabled"
        fi
        ;;

    *)
        usage
        ;;
esac
