#!/bin/bash

usage() {
    printf "Usage: windownamescrolled <max_name_length> <scroll_interval>\n"
    exit 1
}

if [[ ! $1 ]]; then
    usage
fi

if [[ ! $2 ]]; then
    usage
fi

zscroll --update-check true --update-interval 0.1 -l $1 -d $2 "bash $HOME/.config/herbstluftwm/scripts/windowname"
