#!/bin/bash

declare -A roman_nums=( ["1"]="I" ["2"]="II" ["3"]="III" ["4"]="IV" ["5"]="V" ["6"]="VI" ["7"]="VII" ["8"]="VIII" )
declare -A num_widths=( ["1"]="27" ["2"]="36" ["3"]="45" ["4"]="36" ["5"]="27" ["6"]="36" ["7"]="45" ["8"]="54" )

workspaces=($(herbstclient tag_status))
buffered=""
full=""
id=1

for workspace in $workspaces; do
    if echo $workspace | grep '\.' > /dev/null; then
        status="empty"
    elif echo $workspace | grep '\:' > /dev/null; then
        status="occupied"
    elif echo $workspace | grep '\#' > /dev/null; then
        status="active"
    elif echo $workspace | grep '\!' > /dev/null; then
        status="urgent"
    else
        status="other"
    fi

    buffered+="(button :class \"$status\" :height 27 :width ${num_widths[$id]} :onclick \"herbstclient use $id\" \"${roman_nums[$id]}\")"
    full+="$buffered"
    buffered=""

    id="$(expr $id + 1)"
done

box_attrs=':class "workspaces" :orientation "h" :space-evenly false :halign "start" '

eww update workspaces_literal="(box $box_attrs $full)"
